// BuildGuard Pro - Comprehensive Demo Data
// Realistic scenario: Villa Al Barari, 1.75M AED, Dubai

import type {
  Project, ConstructionStage, Deviation, PaymentGate, 
  VariationOrder, Snag, PhotoCapture, HealthScore,
  BIMModel, User, Contractor, Consultant
} from '@/types';

// Users
export const demoHomeowner: User = {
  id: 'usr-001',
  uaePassId: '784-1990-1234567-1',
  name: 'Mohammed Al Mansouri',
  email: 'm.almansouri@email.ae',
  phone: '+971 50 123 4567',
  role: 'homeowner',
};

export const demoContractor: Contractor = {
  id: 'cont-001',
  name: 'Al Futtaim Construction LLC',
  license: 'C-12345-Dubai',
  rating: 4.2,
  projectsCompleted: 47,
  onTimeRate: 0.78,
  qualityScore: 4.1,
  contact: {
    name: 'Ahmad Hassan',
    phone: '+971 55 987 6543',
    email: 'ahmad.h@alfuttaim-construction.ae',
  },
};

export const demoConsultant: Consultant = {
  id: 'consult-001',
  name: 'Engineering Consultants Group',
  license: 'ENG-8821-Dubai',
  email: 'projects@ecg.ae',
};

// BIM Model
export const demoBIMModel: BIMModel = {
  id: 'model-001',
  projectId: 'proj-001',
  name: 'Villa Al Barari - Design Model',
  format: 'ifc',
  lod: 400,
  url: '/models/villa-al-barari-lod400.ifc',
  thumbnail: '/thumbnails/model-001.png',
  size: 156780234,
  uploadedAt: '2026-01-10T08:30:00Z',
  version: 1,
  status: 'approved',
  elements: [
    {
      id: 'elem-001',
      globalId: '3k7v9x2m5p8q1r4',
      type: 'IfcWall',
      name: 'Wall-Living-01',
      category: 'architecture',
      level: 'Ground Floor',
      position: { x: 0, y: 0, z: 0 },
      dimensions: { width: 5000, height: 3200, depth: 200 },
      material: 'Concrete Block',
      properties: { fireRating: '2hr', acousticRating: '45dB' },
      changeable: false,
      frozen: true,
    },
    {
      id: 'elem-002',
      globalId: '7n3w8y4z6a9b2c5',
      type: 'IfcColumn',
      name: 'Column-C3',
      category: 'structural',
      level: 'Ground Floor',
      position: { x: 5000, y: 0, z: 3000 },
      dimensions: { width: 300, height: 3200, depth: 300 },
      material: 'Reinforced Concrete',
      properties: { concreteGrade: 'C40', rebar: '8-T16' },
      changeable: false,
      frozen: true,
    },
    {
      id: 'elem-003',
      globalId: '1d4e7f0g3h6i9j2',
      type: 'IfcWindow',
      name: 'Window-Master-01',
      category: 'architecture',
      level: 'First Floor',
      position: { x: 2000, y: 3000, z: 1500 },
      dimensions: { width: 1800, height: 1500, depth: 100 },
      material: 'Aluminum Frame',
      properties: { uValue: 1.8, glazing: 'Double Low-E' },
      changeable: true,
      frozen: false,
    },
  ],
  metadata: {
    sourceSoftware: 'Autodesk Revit 2024',
    exportDate: '2026-01-10T08:30:00Z',
    unitSystem: 'metric',
    coordinateSystem: 'WGS84-UTM40N',
    northDirection: 15.5,
  },
};

// Project
export const demoProject: Project = {
  id: 'proj-001',
  name: 'Villa Al Barari',
  address: 'Plot B12, Sector 4, Al Barari, Dubai',
  location: 'Dubai',
  plotNumber: 'B12-Sector4',
  permitNumber: 'BP-2026-15432',
  teyaseerId: 'TEY-2026-8842',
  status: 'active',
  progress: 35.5,
  contractValue: 1750000,
  startDate: '2026-01-15',
  expectedCompletion: '2026-12-31',
  homeowner: demoHomeowner,
  contractor: demoContractor,
  consultant: demoConsultant,
  model: demoBIMModel,
};

// Construction Stages
export const demoStages: ConstructionStage[] = [
  {
    id: 'stage-001',
    projectId: 'proj-001',
    name: 'Mobilization & Site Setup',
    sequence: 1,
    status: 'approved',
    progressPercentage: 100,
    paymentPercentage: 2,
    paymentAmount: 35000,
    startDate: '2026-01-15',
    completionDate: '2026-01-25',
    expectedDuration: 10,
    checklist: [
      { id: 'chk-001', description: 'Site clearance and fencing', completed: true, completedAt: '2026-01-16', verifiedBy: 'Eng. Khalid', required: true },
      { id: 'chk-002', description: 'Temporary facilities setup', completed: true, completedAt: '2026-01-18', verifiedBy: 'Eng. Khalid', required: true },
      { id: 'chk-003', description: 'Site signage and safety equipment', completed: true, completedAt: '2026-01-20', verifiedBy: 'Eng. Khalid', required: true },
      { id: 'chk-004', description: 'Utilities temporary connection', completed: true, completedAt: '2026-01-22', verifiedBy: 'Eng. Khalid', required: true },
    ],
    dependencies: [],
    modelElements: [],
  },
  {
    id: 'stage-002',
    projectId: 'proj-001',
    name: 'Excavation & Shoring',
    sequence: 2,
    status: 'approved',
    progressPercentage: 100,
    paymentPercentage: 5,
    paymentAmount: 87500,
    startDate: '2026-01-26',
    completionDate: '2026-02-15',
    expectedDuration: 20,
    checklist: [
      { id: 'chk-005', description: 'Excavation to required depth (-3.5m)', completed: true, completedAt: '2026-02-05', verifiedBy: 'Eng. Khalid', required: true },
      { id: 'chk-006', description: 'Soil testing and lab reports', completed: true, completedAt: '2026-02-08', verifiedBy: 'SoilTest Labs', required: true },
      { id: 'chk-007', description: 'Shoring installation', completed: true, completedAt: '2026-02-12', verifiedBy: 'Eng. Khalid', required: true },
      { id: 'chk-008', description: 'Dewatering system operational', completed: true, completedAt: '2026-02-14', verifiedBy: 'Eng. Khalid', required: true },
    ],
    dependencies: ['stage-001'],
    modelElements: [],
  },
  {
    id: 'stage-003',
    projectId: 'proj-001',
    name: 'Foundation & Substructure',
    sequence: 3,
    status: 'in_progress',
    progressPercentage: 65,
    paymentPercentage: 8,
    paymentAmount: 140000,
    startDate: '2026-02-16',
    expectedDuration: 45,
    checklist: [
      { id: 'chk-009', description: 'Piling works complete', completed: true, completedAt: '2026-02-28', verifiedBy: 'Eng. Khalid', required: true },
      { id: 'chk-010', description: 'Foundation reinforcement', completed: true, completedAt: '2026-03-05', verifiedBy: 'Eng. Khalid', required: true },
      { id: 'chk-011', description: 'Concrete pouring (raft slab)', completed: false, required: true },
      { id: 'chk-012', description: 'Waterproofing membrane', completed: false, required: true },
      { id: 'chk-013', description: 'Backfilling and compaction', completed: false, required: true },
    ],
    dependencies: ['stage-002'],
    modelElements: ['elem-002'],
  },
  {
    id: 'stage-004',
    projectId: 'proj-001',
    name: 'Superstructure (Columns/Beams/Slabs)',
    sequence: 4,
    status: 'not_started',
    progressPercentage: 0,
    paymentPercentage: 15,
    paymentAmount: 262500,
    expectedDuration: 60,
    checklist: [
      { id: 'chk-014', description: 'Column reinforcement', completed: false, required: true },
      { id: 'chk-015', description: 'Column formwork and pouring', completed: false, required: true },
      { id: 'chk-016', description: 'Beam and slab formwork', completed: false, required: true },
      { id: 'chk-017', description: 'Slab reinforcement and pouring', completed: false, required: true },
      { id: 'chk-018', description: 'Curing period (14 days)', completed: false, required: true },
    ],
    dependencies: ['stage-003'],
    modelElements: ['elem-002'],
  },
  {
    id: 'stage-005',
    projectId: 'proj-001',
    name: 'Blockwork & Plaster',
    sequence: 5,
    status: 'not_started',
    progressPercentage: 0,
    paymentPercentage: 10,
    paymentAmount: 175000,
    expectedDuration: 40,
    checklist: [
      { id: 'chk-019', description: 'External blockwork', completed: false, required: true },
      { id: 'chk-020', description: 'Internal blockwork', completed: false, required: true },
      { id: 'chk-021', description: 'Plastering (internal)', completed: false, required: true },
      { id: 'chk-022', description: 'External rendering', completed: false, required: true },
    ],
    dependencies: ['stage-004'],
    modelElements: ['elem-001'],
  },
  {
    id: 'stage-006',
    projectId: 'proj-001',
    name: 'MEP Rough-in',
    sequence: 6,
    status: 'not_started',
    progressPercentage: 0,
    paymentPercentage: 12,
    paymentAmount: 210000,
    expectedDuration: 50,
    checklist: [
      { id: 'chk-023', description: 'Electrical conduits', completed: false, required: true },
      { id: 'chk-024', description: 'Plumbing pipes', completed: false, required: true },
      { id: 'chk-025', description: 'HVAC ductwork', completed: false, required: true },
      { id: 'chk-026', description: 'Fire protection system', completed: false, required: true },
      { id: 'chk-027', description: 'Low voltage cabling', completed: false, required: false },
    ],
    dependencies: ['stage-005'],
    modelElements: [],
  },
  {
    id: 'stage-007',
    projectId: 'proj-001',
    name: 'Finishing Works',
    sequence: 7,
    status: 'not_started',
    progressPercentage: 0,
    paymentPercentage: 20,
    paymentAmount: 350000,
    expectedDuration: 70,
    checklist: [
      { id: 'chk-028', description: 'Flooring installation', completed: false, required: true },
      { id: 'chk-029', description: 'Painting (internal/external)', completed: false, required: true },
      { id: 'chk-030', description: 'Kitchen installation', completed: false, required: true },
      { id: 'chk-031', description: 'Bathroom fixtures', completed: false, required: true },
      { id: 'chk-032', description: 'Door and window installation', completed: false, required: true },
    ],
    dependencies: ['stage-006'],
    modelElements: ['elem-003'],
  },
  {
    id: 'stage-008',
    projectId: 'proj-001',
    name: 'External Works',
    sequence: 8,
    status: 'not_started',
    progressPercentage: 0,
    paymentPercentage: 8,
    paymentAmount: 140000,
    expectedDuration: 30,
    checklist: [
      { id: 'chk-033', description: 'Landscaping', completed: false, required: true },
      { id: 'chk-034', description: 'Driveway and walkways', completed: false, required: true },
      { id: 'chk-035', description: 'Boundary wall and gates', completed: false, required: true },
      { id: 'chk-036', description: 'External lighting', completed: false, required: true },
    ],
    dependencies: ['stage-007'],
    modelElements: [],
  },
  {
    id: 'stage-009',
    projectId: 'proj-001',
    name: 'Final Completion & Handover',
    sequence: 9,
    status: 'not_started',
    progressPercentage: 0,
    paymentPercentage: 20,
    paymentAmount: 350000,
    expectedDuration: 20,
    checklist: [
      { id: 'chk-037', description: 'Snagging list completion', completed: false, required: true },
      { id: 'chk-038', description: 'Final cleaning', completed: false, required: true },
      { id: 'chk-039', description: 'Final inspection', completed: false, required: true },
      { id: 'chk-040', description: 'Handover documentation', completed: false, required: true },
      { id: 'chk-041', description: 'Keys and access cards', completed: false, required: true },
    ],
    dependencies: ['stage-008'],
    modelElements: [],
  },
];

// Deviations
export const demoDeviations: Deviation[] = [
  {
    id: 'dev-001',
    projectId: 'proj-001',
    elementId: 'elem-002',
    elementType: 'column',
    severity: 'critical',
    status: 'detected',
    detectedAt: '2026-03-05T14:20:00Z',
    detectedBy: 'AI Analysis',
    location: 'Ground Floor - Column C3',
    description: 'Structural column misalignment detected. Position deviates 68mm from approved design, exceeding tolerance of ±15mm. This affects load distribution and must be rectified before proceeding with superstructure.',
    expectedPosition: { x: 5000, y: 0, z: 3000 },
    actualPosition: { x: 5068, y: 0, z: 3000 },
    deviationMm: 68,
    toleranceMm: 15,
    photos: ['photo-003', 'photo-004'],
  },
  {
    id: 'dev-002',
    projectId: 'proj-001',
    elementId: 'elem-001',
    elementType: 'wall',
    severity: 'major',
    status: 'under_review',
    detectedAt: '2026-03-01T10:30:00Z',
    detectedBy: 'homeowner',
    location: 'Ground Floor - Living Room North Wall',
    description: 'Living room wall position deviated from approved plans. Wall is offset by 45mm from design position.',
    expectedPosition: { x: 0, y: 0, z: 0 },
    actualPosition: { x: 45, y: 0, z: 0 },
    deviationMm: 45,
    toleranceMm: 20,
    photos: ['photo-001', 'photo-002'],
    reviewedBy: 'Eng. Khalid',
    reviewedAt: '2026-03-03T09:15:00Z',
    resolutionNotes: 'Under investigation. Contractor claims field adjustment was necessary due to site conditions.',
  },
  {
    id: 'dev-003',
    projectId: 'proj-001',
    elementId: 'elem-003',
    elementType: 'window',
    severity: 'minor',
    status: 'rectified',
    detectedAt: '2026-02-20T16:45:00Z',
    detectedBy: 'consultant',
    location: 'First Floor - Master Bedroom',
    description: 'Master bedroom window frame position slightly off from design specification.',
    expectedPosition: { x: 2000, y: 3000, z: 1500 },
    actualPosition: { x: 2018, y: 3000, z: 1500 },
    deviationMm: 18,
    toleranceMm: 10,
    photos: ['photo-005'],
    reviewedBy: 'Eng. Khalid',
    reviewedAt: '2026-02-22T11:00:00Z',
    resolutionNotes: 'Window frame repositioned within tolerance. Verified on 2026-02-25.',
    resolvedAt: '2026-02-25T14:00:00Z',
  },
];

// Payment Gates
export const demoPayments: PaymentGate[] = [
  {
    id: 'pay-001',
    projectId: 'proj-001',
    stageId: 'stage-001',
    name: 'Mobilization & Site Setup',
    amount: 35000,
    status: 'released',
    canRelease: true,
    releaseDate: '2026-01-28',
    blockReasons: [],
    milestone: 'Site setup complete and approved by consultant',
    retentionPercentage: 5,
  },
  {
    id: 'pay-002',
    projectId: 'proj-001',
    stageId: 'stage-002',
    name: 'Excavation & Shoring',
    amount: 87500,
    status: 'released',
    canRelease: true,
    releaseDate: '2026-02-18',
    blockReasons: [],
    milestone: 'Excavation complete and soil approved',
    retentionPercentage: 5,
  },
  {
    id: 'pay-003',
    projectId: 'proj-001',
    stageId: 'stage-003',
    name: 'Foundation & Substructure',
    amount: 140000,
    status: 'pending',
    canRelease: false,
    blockReasons: [
      'Stage not yet approved (65% complete)',
      'Critical deviation unresolved: Column C3 misalignment (68mm)',
      'Required checklist items incomplete',
    ],
    milestone: 'Foundation complete, waterproofed, and approved',
    retentionPercentage: 5,
  },
  {
    id: 'pay-004',
    projectId: 'proj-001',
    stageId: 'stage-004',
    name: 'Superstructure',
    amount: 262500,
    status: 'held',
    canRelease: false,
    blockReasons: ['Previous stage not approved', 'Critical deviation blocking progress'],
    milestone: 'Structure complete, cured, and approved',
    retentionPercentage: 5,
  },
];

// Variation Orders
export const demoVOs: VariationOrder[] = [
  {
    id: 'vo-001',
    projectId: 'proj-001',
    voNumber: 'VO-2026-001',
    title: 'Additional Landscape Features',
    description: 'Homeowner requested additional palm trees and water feature in garden area.',
    type: 'addition',
    status: 'approved',
    requestedBy: 'homeowner',
    requestedAt: '2026-02-15T10:00:00Z',
    costImpact: 45000,
    scheduleImpact: 5,
    approvedBy: 'consultant',
    approvedAt: '2026-02-18T14:30:00Z',
    modelVersion: 2,
    attachments: ['landscape-plan-v2.pdf'],
    relatedElements: [],
  },
  {
    id: 'vo-002',
    projectId: 'proj-001',
    voNumber: 'VO-2026-002',
    title: 'Upgrade Kitchen Countertops',
    description: 'Change from standard granite to imported Italian marble.',
    type: 'substitution',
    status: 'under_review',
    requestedBy: 'homeowner',
    requestedAt: '2026-03-01T09:00:00Z',
    costImpact: 28000,
    scheduleImpact: 0,
    attachments: ['marble-sample.pdf', 'supplier-quote.pdf'],
    relatedElements: ['elem-kitchen-01'],
  },
];

// Snags
export const demoSnags: Snag[] = [
  {
    id: 'snag-001',
    projectId: 'proj-001',
    title: 'Paint touch-up required - Living room',
    description: 'Minor paint chips and uneven finish on north wall of living room.',
    type: 'cosmetic',
    severity: 'low',
    status: 'open',
    area: 'Living Room',
    reportedBy: 'homeowner',
    reportedAt: '2026-03-10T11:00:00Z',
    photos: ['snag-001-01.jpg'],
  },
  {
    id: 'snag-002',
    projectId: 'proj-001',
    title: 'Electrical outlet not working',
    description: 'Master bedroom outlet near window has no power.',
    type: 'mep',
    severity: 'medium',
    status: 'assigned',
    area: 'Master Bedroom',
    reportedBy: 'homeowner',
    reportedAt: '2026-03-08T16:30:00Z',
    assignedTo: 'MEP Contractor',
    assignedAt: '2026-03-09T09:00:00Z',
    dueDate: '2026-03-12',
    photos: ['snag-002-01.jpg'],
  },
];

// Photo Captures
export const demoPhotos: PhotoCapture[] = [
  {
    id: 'photo-001',
    projectId: 'proj-001',
    sessionId: 'session-001',
    url: '/photos/foundation-001.jpg',
    thumbnail: '/thumbnails/foundation-001.jpg',
    caption: 'Foundation reinforcement - North side view',
    capturedAt: '2026-03-01T10:30:00Z',
    capturedBy: 'homeowner',
    stageId: 'stage-003',
    location: { lat: 24.4539, lng: 54.3773, accuracy: 3.2 },
    aiAnalysis: {
      qualityScore: 7.5,
      issuesDetected: ['rebar_spacing_inconsistent'],
      elementsDetected: ['rebar', 'formwork', 'concrete'],
      progressEstimate: 65,
      complianceStatus: 'attention_needed',
      recommendations: ['Verify rebar spacing meets specification', 'Check concrete cover thickness'],
    },
    tags: ['foundation', 'rebar', 'inspection'],
    relatedDeviationId: 'dev-002',
  },
  {
    id: 'photo-002',
    projectId: 'proj-001',
    sessionId: 'session-001',
    url: '/photos/foundation-002.jpg',
    thumbnail: '/thumbnails/foundation-002.jpg',
    caption: 'Foundation reinforcement - South side view',
    capturedAt: '2026-03-01T10:35:00Z',
    capturedBy: 'homeowner',
    stageId: 'stage-003',
    location: { lat: 24.4539, lng: 54.3773, accuracy: 2.8 },
    aiAnalysis: {
      qualityScore: 8.2,
      issuesDetected: [],
      elementsDetected: ['rebar', 'formwork'],
      progressEstimate: 65,
      complianceStatus: 'compliant',
      recommendations: [],
    },
    tags: ['foundation', 'rebar'],
    relatedDeviationId: 'dev-002',
  },
  {
    id: 'photo-003',
    projectId: 'proj-001',
    sessionId: 'session-002',
    url: '/photos/column-deviation.jpg',
    thumbnail: '/thumbnails/column-deviation.jpg',
    caption: 'Column C3 - Position verification with AR overlay',
    capturedAt: '2026-03-05T14:20:00Z',
    capturedBy: 'homeowner',
    stageId: 'stage-003',
    location: { lat: 24.4539, lng: 54.3773, accuracy: 2.1 },
    cameraPose: {
      position: { x: 4.8, y: 1.5, z: 2.9 },
      rotation: { x: 0.1, y: -0.3, z: 0, w: 0.95 },
      fov: 60,
    },
    aiAnalysis: {
      qualityScore: 9.0,
      issuesDetected: ['position_deviation', 'alignment_error'],
      elementsDetected: ['column', 'rebar', 'formwork'],
      progressEstimate: 70,
      complianceStatus: 'non_compliant',
      recommendations: ['Immediate structural review required', 'Do not proceed with superstructure'],
    },
    tags: ['column', 'deviation', 'critical', 'ar-overlay'],
    relatedDeviationId: 'dev-001',
  },
  {
    id: 'photo-004',
    projectId: 'proj-001',
    sessionId: 'session-003',
    url: '/photos/column-detail.jpg',
    thumbnail: '/thumbnails/column-detail.jpg',
    caption: 'Column C3 - Close-up of reinforcement',
    capturedAt: '2026-03-05T14:25:00Z',
    capturedBy: 'consultant',
    stageId: 'stage-003',
    location: { lat: 24.4539, lng: 54.3773, accuracy: 1.8 },
    aiAnalysis: {
      qualityScore: 8.8,
      issuesDetected: [],
      elementsDetected: ['column', 'rebar', 'concrete'],
      complianceStatus: 'compliant',
      recommendations: [],
    },
    tags: ['column', 'detail'],
    relatedDeviationId: 'dev-001',
  },
  {
    id: 'photo-005',
    projectId: 'proj-001',
    sessionId: 'session-004',
    url: '/photos/window-rectified.jpg',
    thumbnail: '/thumbnails/window-rectified.jpg',
    caption: 'Master bedroom window - After rectification',
    capturedAt: '2026-02-25T14:00:00Z',
    capturedBy: 'contractor',
    stageId: 'stage-005',
    location: { lat: 24.4539, lng: 54.3773, accuracy: 2.5 },
    aiAnalysis: {
      qualityScore: 9.2,
      issuesDetected: [],
      elementsDetected: ['window', 'frame', 'glass'],
      complianceStatus: 'compliant',
      recommendations: [],
    },
    tags: ['window', 'rectified'],
    relatedDeviationId: 'dev-003',
  },
];

// Health Score
export const demoHealthScore: HealthScore = {
  overall: 72,
  schedule: { score: 65, status: 'at_risk', daysBehind: 5 },
  quality: { score: 78, status: 'good', openIssues: 2 },
  budget: { score: 85, status: 'excellent', variancePct: 2 },
  documentation: { score: 90, status: 'excellent', completionPct: 95 },
  communication: { score: 60, status: 'attention_needed', responseHours: 48 },
  recommendations: [
    'CRITICAL: Address column C3 misalignment before proceeding with superstructure',
    'Schedule weekly progress meetings to improve communication',
    'Request contractor to provide revised timeline for foundation completion',
    'Review wall deviation with structural engineer',
  ],
};

// Notifications
export const demoNotifications = [
  {
    id: 'notif-001',
    userId: 'usr-001',
    type: 'deviation_detected',
    title: 'Critical Deviation Detected',
    message: 'Column C3 is misaligned by 68mm. Immediate action required.',
    data: { deviationId: 'dev-001' },
    read: false,
    createdAt: '2026-03-05T14:20:00Z',
    priority: 'critical',
  },
  {
    id: 'notif-002',
    userId: 'usr-001',
    type: 'payment_ready',
    title: 'Payment Blocked',
    message: 'Foundation stage payment (140,000 AED) is blocked due to unresolved deviations.',
    data: { paymentId: 'pay-003' },
    read: false,
    createdAt: '2026-03-06T09:00:00Z',
    priority: 'high',
  },
  {
    id: 'notif-003',
    userId: 'usr-001',
    type: 'stage_approved',
    title: 'Stage Approved',
    message: 'Excavation & Shoring stage has been approved.',
    data: { stageId: 'stage-002' },
    read: true,
    createdAt: '2026-02-16T10:00:00Z',
    priority: 'medium',
  },
];

// Export for easy access
export const demoData = {
  project: demoProject,
  stages: demoStages,
  deviations: demoDeviations,
  payments: demoPayments,
  vos: demoVOs,
  snags: demoSnags,
  photos: demoPhotos,
  healthScore: demoHealthScore,
  notifications: demoNotifications,
};
